### ISSUE TITLE
Send an email to user after provisioning completes

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#381]
Upon successful provisioning, we should send an email to the user welcoming them to use the Sandbox and next steps that also include all relevant URLs.

**Comment by Daniel-Sanche** [comment]
@simonz130 Do you have any ideas in mind for how to implement this? It looks like [the docs](https://cloud.google.com/compute/docs/tutorials/sending-mail/) recommend using 3rd party services. That could cause issues since customers own their sandbox projects, we don't want to force them to create new accounts on other services

**Comment by nicoleczhu** [comment]
To @Daniel-Sanche 's point, I don't think we should build custom email server bc: 
1. Maintaining custom email servers is very involved, i.e. just to bypass spam filters
2. It doesn't add to Sandbox's main goal of showcasing observability/cloud features
3. It adds to the install time & friction of starting a new Sandbox.

Asking users to use a 3rd party service is also too frictioned and seems like we're endorsing sendgrid/mailgun etc. 

I'm currently looking into ways where users can opt into email notifications within GCP. We could also run our own email account and relay things through gmail, but that introduces privacy hurdles since we're essentially subscribing users. 

Thoughts @simonz130 ?
