### ISSUE TITLE
Add --skip-authentication flag to sandboxctl CLI tool 

### ISSUE THREAD

**Issue by vishal84** [GoogleCloudPlatform/cloud-ops-sandbox#742]
To support use cases where a consumer of the cloud-ops-sandbox has an existing project and wants to provision the repo using a compute engine VM that has a service account tied to it with elevated privileges, it would be nice to be able to use a flag --skip-authentication to skip the auth check in the sandboxctl create method to prevent the need for interactivity using the CLI.

**Comment by daniel-sanche** [comment]
We do have a [`--project` flag](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/1351767277269dcf0e76bb2a4e5fe08c8dd89f3b/terraform/install.sh#L378) in place. When that is set, the script will skip all authentication steps and go straight to deployment. We use this as part of our CI so that no user interaction is needed. Does that match what you're looking for?

**Comment by vishal84** [comment]
that should work, let me re-test this but I had issues with this previously.  I will update here when I get a chance to test out again.

**Comment by daniel-sanche** [comment]
As an update: after some testing, it looks like the issue came down to us using different terraform versions. The install script didn't support v1.0.0 (although we have an open PR for that [here](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/759))
