### ISSUE TITLE
Refactor TF - Verify no multiple resources are created.

### ISSUE THREAD

**Issue by Ayelet41** [GoogleCloudPlatform/cloud-ops-sandbox#790]
If the Cloud Shell closes a way to get it back up without it running through the environment provisioning.  We talked about this the other day where some of the resources get duplicated when doing this.

**Comment by daniel-sanche** [comment]
related issue: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/453

**Comment by minherz** [comment]
This issue wan't be fixed because the next versions of Sandbox will integrate with existing installation of Online Boutique instead of maintaining local version of its older version, Hipster shop. In result, there will be no resource duplication since enrolling the demo application will not be a part of the Sandbox enrollment process.
